name: Pipeline de Testes

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Yarn
        run: npm install -g yarn

      - name: Instalar dependências
        run: yarn install

      - name: Criar pasta de relatórios
        run: mkdir -p relatorios

      - name: Executar testes e gerar relatório
        run: yarn test:report

      - name: Upload do relatório
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-mocha
          path: relatorios/